name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Test Discovery
        run: |
          echo "Python Version:"
          python --version

          echo "Current Working Directory:"
          pwd

          echo "Listing All Files in the Repository:"
          ls -R

          echo "Listing Files in Tests Directory:"
          ls -R tests

          echo "Checking Python Path:"
          echo $PYTHONPATH

          echo "Running Test Discovery:"
          python -m unittest discover tests -v

      - name: Run tests
        run: python -m unittest discover tests -v
